blank_issues_enabled: true
contact_links:
  - name: âœ‰ï¸ My contacts
    url: https://linktr.ee/BennyExtreme
    about: Open the list of all my contacts
  - name: ğŸ”— Main repository
    url: https://github.com/Soneliem/WAIUA
    about: Open the main repository from Sonel (Soneliem)
